@startuml
title 公司人员管理系统活动图

start
:系统启动;

if (用户身份是系统管理员?) then (是)
    :配置系统基础设置（如权限、部门等）;
    :录入初始员工信息;
    :设置考勤规则与绩效模板;
    :维护系统数据（定期更新等）;
else if (用户身份是部门经理?) then (是)
    :查看部门员工信息;
    if (有员工请假申请?) then (是)
        :审批员工请假申请;
    endif
    if (到绩效评估周期?) then (是)
        :对部门员工进行绩效评估;
    endif
    :查看部门考勤统计;
else (用户身份是普通员工?)
    :登录系统;
    :查看个人信息;
    if (需要请假?) then (是)
        :填写请假申请并提交;
    endif
    if (想查看绩效成绩?) then (是)
        :查看个人绩效成绩;
    endif
endif

stop
@enduml